# Generated by Django 4.0.4 on 2022-05-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activeuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'ActiveUser',
            },
        ),
        migrations.CreateModel(
            name='studentaffairsadmin',
            fields=[
                ('nationalnum', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('dateofbirth', models.DateField()),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'AdminsData',
            },
        ),
        migrations.CreateModel(
            name='studentdataa',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('nationalnum', models.CharField(max_length=14, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('dateofbirth', models.DateField()),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('level', models.CharField(max_length=2)),
                ('department', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'StudentsData',
            },
        ),
    ]
